(("default" . ((user-emacs-directory . "~/.emacs.default")))
 ("spacemacs" . ((user-emacs-directory . "~/spacemacs" )
                 env . (("SPACEMACSDIR" . "~/.spacemacs.d"))))
 ("doom" . ((user-emacs-directory . "~/doom-emacs")
            (env . (("DOOMDIR" . "~/.doom.d"))))))
